import { useState, useMemo, useRef, useEffect } from "react";
import { pdf, Document, Page, View, Text, Image, Link, StyleSheet } from "@react-pdf/renderer";

const accent = "#00D4AA";
const bg = "#07080A";
const border = "#1A1D1E";
const textPrimary = "#F1F1F3";
const textSecondary = "#8B8B93";
const textMuted = "#5C5C66";
const fail = "#EF4444";
const warning = "#F59E0B";

function statusColor(s: string): string {
  if (s === "pass") return accent;
  if (s === "fail") return fail;
  if (s === "warning") return warning;
  return textMuted;
}

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: "Helvetica", backgroundColor: bg, color: textPrimary },
  header: { marginBottom: 24, borderBottom: `1 solid ${border}`, paddingBottom: 16 },
  title: { fontSize: 24, fontWeight: "bold", color: accent, marginBottom: 4 },
  subtitle: { fontSize: 10, color: textSecondary },
  frameworkHeader: { fontSize: 14, fontWeight: "bold", color: accent, marginBottom: 4, marginTop: 4 },
  frameworkMeta: { fontSize: 9, color: textMuted, marginBottom: 8 },
  tableHeader: { borderBottom: `1 solid ${border}`, paddingBottom: 4, marginBottom: 4, flexDirection: "row" },
  tableHeaderText: { fontSize: 8, fontWeight: "bold", color: textMuted },
  row: { flexDirection: "row", paddingVertical: 3, borderBottom: `1 solid ${border}`, alignItems: "center" },
  cellControl: { width: "18%", fontSize: 8, fontFamily: "Courier", color: textSecondary },
  cellTitle: { width: "42%", fontSize: 8, color: textPrimary },
  cellStatus: { width: "12%", fontSize: 8 },
  cellDetail: { width: "28%", fontSize: 7, color: textMuted },
  footer: { fontSize: 8, color: textMuted, marginTop: 32, borderTop: `1 solid ${border}`, paddingTop: 12 },
  accentBar: { backgroundColor: accent, height: 3, width: 40, marginBottom: 12 },
});

function ReportPdf({ appUrl, orgName, date, frameworks }: { appUrl: string; orgName: string; date: string; frameworks: { framework: string; controls: { controlId: string; title: string; status: string; detail: string | null }[] }[] }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <View style={{ flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 8 }}>
            <Image source="/icon.png" style={{ width: 28, height: 28 }} />
            <Text style={styles.title}>Compliance Report</Text>
            <View style={{ backgroundColor: "#00D4AA", borderRadius: 4, paddingHorizontal: 6, paddingVertical: 3 }}>
              <Text style={{ fontSize: 7, fontWeight: "bold", color: "#000" }}>AI-GENERATED</Text>
            </View>
          </View>
          <View style={styles.accentBar} />
          <Text style={styles.subtitle}>{orgName} — {date}</Text>
        </View>

        {frameworks.map((fw) => {
          const verified = fw.controls.filter((c) => c.status === "pass").length;
          const failedC = fw.controls.filter((c) => c.status === "fail").length;
          const warnings = fw.controls.filter((c) => c.status === "warning").length;

          return (
            <View key={fw.framework} style={{ marginBottom: 20 }}>
              <Text style={styles.frameworkHeader}>
                {fw.framework === "soc2" ? "SOC 2" : "EU AI Act"}
              </Text>
              <Text style={styles.frameworkMeta}>
                {fw.controls.length} controls — {verified} passed, {failedC} failed, {warnings} warnings
              </Text>

              <View style={styles.tableHeader}>
                <Text style={{ ...styles.tableHeaderText, width: "18%" }}>Control</Text>
                <Text style={{ ...styles.tableHeaderText, width: "42%" }}>Title</Text>
                <Text style={{ ...styles.tableHeaderText, width: "12%" }}>Status</Text>
                <Text style={{ ...styles.tableHeaderText, width: "28%" }}>Detail</Text>
              </View>

              {fw.controls.map((r) => (
                <View key={r.controlId} style={styles.row}>
                  <Text style={styles.cellControl}>{r.controlId}</Text>
                  <Text style={styles.cellTitle}>{r.title}</Text>
                  <Text style={{ ...styles.cellStatus, color: statusColor(r.status) }}>{r.status}</Text>
                  <Text style={styles.cellDetail}>{r.detail || "—"}</Text>
                </View>
              ))}
            </View>
          );
        })}

        <Text style={styles.footer}>Generated by <Link src={appUrl} style={{ color: accent, textDecoration: "none" }}>Spire</Link></Text>
      </Page>
    </Document>
  );
}

function useStablePdf(doc: ReturnType<typeof ReportPdf>) {
  const [url, setUrl] = useState<string | null>(null);
  const ref = useRef<ReturnType<typeof pdf> | null>(null);

  useEffect(() => {
    ref.current = pdf(doc);
    ref.current.toBlob().then((blob: Blob) => {
      setUrl(URL.createObjectURL(blob));
    });
    return () => {
      if (ref.current) ref.current.toBlob = undefined as any;
    };
    // Only run once — doc is assumed stable
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return url;
}

function QuestionnairePdf({ title, date, questions }: { title: string; date: string; questions: { question: string; answer: string; confidence: number }[] }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <View style={{ flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 8 }}>
            <Image source="/icon.png" style={{ width: 28, height: 28 }} />
            <Text style={styles.title}>Security Questionnaire</Text>
            <View style={{ backgroundColor: accent, borderRadius: 4, paddingHorizontal: 6, paddingVertical: 3 }}>
              <Text style={{ fontSize: 7, fontWeight: "bold", color: "#000" }}>AI-GENERATED</Text>
            </View>
          </View>
          <View style={styles.accentBar} />
          <Text style={styles.subtitle}>{title} — {date}</Text>
        </View>

        {questions.map((q, i) => (
          <View key={i} style={{ marginBottom: 12, borderBottom: `1 solid ${border}`, paddingBottom: 8 }}>
            <Text style={{ fontSize: 10, fontWeight: "bold", color: textPrimary, marginBottom: 2 }}>{i + 1}. {q.question}</Text>
            <Text style={{ fontSize: 9, color: textSecondary, marginBottom: 2 }}>{q.answer || "(no answer)"}</Text>
            <Text style={{ fontSize: 8, color: q.confidence > 0.7 ? accent : q.confidence > 0.4 ? warning : textMuted }}>
              Confidence: {Math.round(q.confidence * 100)}%
            </Text>
          </View>
        ))}

        <Text style={styles.footer}>Generated by Spire — {new Date().toISOString().split("T")[0]}</Text>
      </Page>
    </Document>
  );
}

export function useQuestionnairePdf(title: string, date: string, questions: { question: string; answer: string; confidence: number }[]) {
  const doc = useMemo(() => <QuestionnairePdf title={title} date={date} questions={questions} />, [title, date, questions]);
  const [url, setUrl] = useState<string | null>(null);
  useEffect(() => {
    let cancelled = false;
    pdf(doc).toBlob().then((blob: Blob) => { if (!cancelled) setUrl(URL.createObjectURL(blob)); });
    return () => { cancelled = true; };
  }, [doc]);
  return url;
}

export function DownloadReportButton(props: { appUrl: string; orgName: string; date: string; frameworks: { framework: string; controls: { controlId: string; title: string; status: string; detail: string | null }[] }[] }) {
  const { appUrl, orgName, date, frameworks } = props;
  const [open, setOpen] = useState(false);

  const fullDoc = useMemo(() => <ReportPdf appUrl={appUrl} orgName={orgName} date={date} frameworks={frameworks} />, [appUrl, orgName, date, frameworks]);
  const soc2Doc = useMemo(() => <ReportPdf appUrl={appUrl} orgName={orgName} date={date} frameworks={frameworks.filter((f) => f.framework === "soc2")} />, [appUrl, orgName, date, frameworks]);
  const aiDoc = useMemo(() => <ReportPdf appUrl={appUrl} orgName={orgName} date={date} frameworks={frameworks.filter((f) => f.framework === "ai-act")} />, [appUrl, orgName, date, frameworks]);

  const fullUrl = useStablePdf(fullDoc);
  const soc2Url = useStablePdf(soc2Doc);
  const aiUrl = useStablePdf(aiDoc);
  const hasSoc2 = frameworks.some((f) => f.framework === "soc2");
  const hasAi = frameworks.some((f) => f.framework === "ai-act");

  return (
    <div className="relative">
      <div className="flex">
        <a
          href={fullUrl || "#"}
          download={fullUrl ? `spire-compliance-report-${date}.pdf` : undefined}
          className={`rounded-l-lg border-r-0 border border-[#1A1D1E] px-5 py-2.5 text-sm font-medium text-[#8B8B93] hover:border-[#00D4AA] hover:text-[#00D4AA] transition-all ${!fullUrl ? "pointer-events-none" : ""}`}
        >
          {fullUrl ? "Download report" : "Preparing…"}
        </a>
        <button onClick={() => setOpen(!open)}
          className="rounded-r-lg border border-[#1A1D1E] px-2.5 py-2.5 text-[#8B8B93] hover:border-[#00D4AA] hover:text-[#00D4AA] transition-all"
        >
          <svg className={`h-3 w-3 transition-transform ${open ? "rotate-180" : ""}`} viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round">
            <path d="M4 6l4 4 4-4" />
          </svg>
        </button>
      </div>
      {open && (
        <>
          <div className="fixed inset-0 z-10" onClick={() => setOpen(false)} />
          <div className="absolute right-0 top-full z-20 mt-1 w-48 overflow-hidden rounded-lg border border-[#1A1D1E] bg-[#0B0D0E] py-1 shadow-lg">
            <div className="px-4 py-1.5 text-[10px] font-semibold uppercase tracking-wider text-[#5C5C66]">Export as</div>
            <a href={fullUrl || "#"} download={fullUrl ? `spire-compliance-report-${date}.pdf` : undefined}
              className="block w-full px-4 py-2 text-left text-xs text-[#8B8B93] hover:bg-[#141718] hover:text-[#F1F1F3] transition-colors"
            >{fullUrl ? "Full report" : "Preparing…"}</a>
            {hasSoc2 && (
              <a href={soc2Url || "#"} download={soc2Url ? `spire-soc2-report-${date}.pdf` : undefined}
                className="block w-full px-4 py-2 text-left text-xs text-[#8B8B93] hover:bg-[#141718] hover:text-[#F1F1F3] transition-colors"
              >{soc2Url ? "SOC 2 only" : "Preparing…"}</a>
            )}
            {hasAi && (
              <a href={aiUrl || "#"} download={aiUrl ? `spire-ai-act-report-${date}.pdf` : undefined}
                className="block w-full px-4 py-2 text-left text-xs text-[#8B8B93] hover:bg-[#141718] hover:text-[#F1F1F3] transition-colors"
              >{aiUrl ? "EU AI Act only" : "Preparing…"}</a>
            )}
          </div>
        </>
      )}
    </div>
  );
}
