import { PDFDownloadLink, Document, Page, View, Text, Image, StyleSheet } from "@react-pdf/renderer";

const accent = "#00D4AA";
const bg = "#07080A";
const surface = "#0B0D0E";
const border = "#1A1D1E";
const textPrimary = "#F1F1F3";
const textSecondary = "#8B8B93";
const textMuted = "#5C5C66";
const fail = "#EF4444";
const warning = "#F59E0B";

function statusColor(s: string): string {
  if (s === "pass") return accent;
  if (s === "fail") return fail;
  if (s === "warning") return warning;
  return textMuted;
}

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: "Helvetica", backgroundColor: bg, color: textPrimary },
  header: { marginBottom: 24, borderBottom: `1 solid ${border}`, paddingBottom: 16 },
  title: { fontSize: 24, fontWeight: "bold", color: accent, marginBottom: 4 },
  subtitle: { fontSize: 10, color: textSecondary },
  frameworkHeader: { fontSize: 14, fontWeight: "bold", color: accent, marginBottom: 4, marginTop: 4 },
  frameworkMeta: { fontSize: 9, color: textMuted, marginBottom: 8 },
  tableHeader: { borderBottom: `1 solid ${border}`, paddingBottom: 4, marginBottom: 4, flexDirection: "row" },
  tableHeaderText: { fontSize: 8, fontWeight: "bold", color: textMuted },
  row: { flexDirection: "row", paddingVertical: 3, borderBottom: `1 solid ${border}` },
  cellControl: { width: "18%", fontSize: 8, fontFamily: "Courier", color: textSecondary },
  cellTitle: { width: "42%", fontSize: 8, color: textPrimary },
  cellStatus: { width: "12%", fontSize: 8 },
  cellDetail: { width: "28%", fontSize: 7, color: textMuted },
  footer: { fontSize: 8, color: textMuted, marginTop: 32, borderTop: `1 solid ${border}`, paddingTop: 12 },
  accentBar: { backgroundColor: accent, height: 3, width: 40, marginBottom: 12 },
});

function ReportPdf({ orgName, date, frameworks }: { orgName: string; date: string; frameworks: { framework: string; controls: { controlId: string; title: string; status: string; detail: string | null }[] }[] }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <View style={{ flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 8 }}>
            <Image source="/icon.png" style={{ width: 28, height: 28 }} />
            <Text style={styles.title}>Compliance Report</Text>
          </View>
          <View style={styles.accentBar} />
          <Text style={styles.subtitle}>{orgName} — {date}</Text>
        </View>

        {frameworks.map((fw) => {
          const verified = fw.controls.filter((c) => c.status === "pass").length;
          const failedC = fw.controls.filter((c) => c.status === "fail").length;
          const warnings = fw.controls.filter((c) => c.status === "warning").length;

          return (
            <View key={fw.framework} style={{ marginBottom: 20 }}>
              <Text style={styles.frameworkHeader}>
                {fw.framework === "soc2" ? "SOC 2" : "EU AI Act"}
              </Text>
              <Text style={styles.frameworkMeta}>
                {fw.controls.length} controls — {verified} passed, {failedC} failed, {warnings} warnings
              </Text>

              <View style={styles.tableHeader}>
                <Text style={{ ...styles.tableHeaderText, width: "18%" }}>Control</Text>
                <Text style={{ ...styles.tableHeaderText, width: "42%" }}>Title</Text>
                <Text style={{ ...styles.tableHeaderText, width: "12%" }}>Status</Text>
                <Text style={{ ...styles.tableHeaderText, width: "28%" }}>Detail</Text>
              </View>

              {fw.controls.map((r) => (
                <View key={r.controlId} style={styles.row}>
                  <Text style={styles.cellControl}>{r.controlId}</Text>
                  <Text style={styles.cellTitle}>{r.title}</Text>
                  <Text style={{ ...styles.cellStatus, color: statusColor(r.status) }}>{r.status}</Text>
                  <Text style={styles.cellDetail}>{r.detail || "—"}</Text>
                </View>
              ))}
            </View>
          );
        })}

        <Text style={styles.footer}>Generated by Spire — compliance-autopilot</Text>
      </Page>
    </Document>
  );
}

export function DownloadReportButton({ orgName, date, frameworks, className }: { orgName: string; date: string; frameworks: { framework: string; controls: { controlId: string; title: string; status: string; detail: string | null }[] }[]; className?: string }) {
  return (
    <PDFDownloadLink
      document={<ReportPdf orgName={orgName} date={date} frameworks={frameworks} />}
      fileName={`spire-compliance-report-${date}.pdf`}
      className={className}
    >
      {({ loading }: { loading: boolean }) => (loading ? "Preparing…" : "Download report")}
    </PDFDownloadLink>
  );
}
