import { renderToStream, Document, Page, View, Text } from "@react-pdf/renderer";
import { db } from "~/db";
import { control, policyCheck } from "~/db/schema";
import { auth } from "~/lib/auth.server";
import { eq } from "drizzle-orm";
import { hasActiveSubscription } from "~/lib/subscription-check";
import type { Route } from "./+types/dashboard.compliance-export";

export async function loader({ request }: Route.LoaderArgs) {
  const session = await auth.api.getSession({ headers: request.headers });
  if (!session) return new Response("Unauthorized", { status: 401 });

  const orgId = session.session.activeOrganizationId!;
  if (!await hasActiveSubscription(orgId, session.user.id)) return new Response("Subscription required", { status: 402 });

  const [allControls, verdicts] = await Promise.all([
    db.select().from(control),
    db.select().from(policyCheck).where(eq(policyCheck.organizationId, orgId)),
  ]);

  const verdictByControl = new Map<string, typeof verdicts[0]>();
  for (const v of verdicts) {
    if (v.ruleId) verdictByControl.set(v.ruleId, v);
  }

  const frameworks = [...new Set(allControls.map((c) => c.framework))];

  const stream = await renderToStream(
    <Document>
      <Page size="A4" style={{ padding: 40, fontFamily: "Helvetica" }}>
        <View style={{ marginBottom: 24 }}>
          <Text style={{ fontSize: 22, fontWeight: "bold", marginBottom: 4 }}>Compliance Report</Text>
          <Text style={{ fontSize: 10, color: "#666" }}>{session.user.name} — {new Date().toISOString().split("T")[0]}</Text>
        </View>

        {frameworks.map((fw) => {
          const fwControls = allControls.filter((c) => c.framework === fw);
          let verified = 0, failed = 0, warnings = 0;
          const rows = fwControls.map((c) => {
            const v = verdictByControl.get(c.controlId);
            if (v?.status === "pass") verified++;
            else if (v?.status === "fail") failed++;
            else if (v?.status === "warning") warnings++;
            return { controlId: c.controlId, title: c.title, status: v?.status || "unchecked", detail: v?.detail || null };
          });

          return (
            <View key={fw} style={{ marginBottom: 20 }}>
              <Text style={{ fontSize: 14, fontWeight: "bold", marginBottom: 6, color: "#111" }}>
                {fw === "soc2" ? "SOC 2" : "EU AI Act"}
              </Text>
              <Text style={{ fontSize: 9, color: "#666", marginBottom: 8 }}>
                {rows.length} controls — {verified} passed, {failed} failed, {warnings} warnings
              </Text>

              <View style={{ borderBottom: "1 solid #ddd", paddingBottom: 4, marginBottom: 4, flexDirection: "row" }}>
                <Text style={{ width: "18%", fontSize: 8, fontWeight: "bold", color: "#444" }}>Control</Text>
                <Text style={{ width: "42%", fontSize: 8, fontWeight: "bold", color: "#444" }}>Title</Text>
                <Text style={{ width: "12%", fontSize: 8, fontWeight: "bold", color: "#444" }}>Status</Text>
                <Text style={{ width: "28%", fontSize: 8, fontWeight: "bold", color: "#444" }}>Detail</Text>
              </View>

              {rows.map((r) => (
                <View key={r.controlId} style={{ flexDirection: "row", paddingVertical: 3, borderBottom: "1 solid #eee" }}>
                  <Text style={{ width: "18%", fontSize: 8, fontFamily: "Courier", color: "#333" }}>{r.controlId}</Text>
                  <Text style={{ width: "42%", fontSize: 8, color: "#333" }}>{r.title}</Text>
                  <Text style={{ width: "12%", fontSize: 8, color: statusColor(r.status) }}>{r.status}</Text>
                  <Text style={{ width: "28%", fontSize: 7, color: "#666" }}>{r.detail || "—"}</Text>
                </View>
              ))}
            </View>
          );
        })}

        <Text style={{ fontSize: 8, color: "#999", marginTop: 32 }}>
          Generated by Spire — compliance-autopilot
        </Text>
      </Page>
    </Document>,
  );

  const chunks: Uint8Array[] = [];
  for await (const chunk of stream) {
    chunks.push(chunk as Uint8Array);
  }
  const totalLength = chunks.reduce((sum, c) => sum + c.length, 0);
  const pdf = new Uint8Array(totalLength);
  let offset = 0;
  for (const c of chunks) { pdf.set(c, offset); offset += c.length; }

  return new Response(pdf, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="spire-compliance-report-${new Date().toISOString().split("T")[0]}.pdf"`,
    },
  });
}

function statusColor(status: string): string {
  if (status === "pass") return "#00D4AA";
  if (status === "fail") return "#EF4444";
  if (status === "warning") return "#F59E0B";
  return "#999";
}
