import { Link } from "react-router";
import { PublicLayout } from "~/components/public-layout";
import { OrganizationSchema } from "~/components/geo-schema";

export function meta() {
  return [
    { title: "Security & Compliance | Spire" },
    { name: "description", content: "Spire's data encryption standards, infrastructure security architecture, and compliance framework for B2B SaaS." },
    { property: "og:title", content: "Security & Compliance | Spire" },
    { property: "og:type", content: "website" },
    { name: "twitter:card", content: "summary_large_image" },
  ];
}

export default function Security() {
  return (
    <PublicLayout>
      <OrganizationSchema />

      <section className="mx-auto max-w-4xl px-6 pt-16 pb-24">
        <span className="text-xs font-semibold uppercase tracking-[0.15em] text-[#00D4AA]">Security & Compliance</span>
        <h1 className="mt-3 text-4xl font-bold tracking-tight text-[#F1F1F3] md:text-5xl">Enterprise-grade security for your compliance data</h1>
        <p className="mt-4 text-lg text-[#8B8B93]">Spire encrypts all data in transit and at rest. We follow SOC 2 best practices and can provide compliance reports generated by our own platform on request.</p>

        <div className="mt-14 grid gap-6 md:grid-cols-2">
          <div className="rounded-xl border border-[#1C1C24] bg-[#111116] p-6">
            <h2 className="text-lg font-bold text-[#F1F1F3]">SOC 2 Aligned</h2>
            <p className="mt-2 text-sm text-[#8B8B93]">Spire is built following SOC 2 trust service criteria. We use our own platform to continuously monitor controls and can generate compliance reports showing current control status against SOC 2 requirements.</p>
            <ul className="mt-4 space-y-2 text-sm text-[#8B8B93]">
              <li className="flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-[#00D4AA]" /> Control monitoring via our own platform</li>
              <li className="flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-[#00D4AA]" /> On-demand compliance reports</li>
              <li className="flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-[#00D4AA]" /> Evidence library with audit trail</li>
              <li className="flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-[#00D4AA]" /> Preparing for formal SOC 2 certification</li>
            </ul>
          </div>
          <div className="rounded-xl border border-[#1C1C24] bg-[#111116] p-6">
            <h2 className="text-lg font-bold text-[#F1F1F3]">EU AI Act Aligned</h2>
            <p className="mt-2 text-sm text-[#8B8B93]">Our AI compliance agent and internal AI governance framework align with EU AI Act requirements including Article 4 AI literacy, Article 50 transparency, and GPAI Code of Practice documentation standards.</p>
            <ul className="mt-4 space-y-2 text-sm text-[#8B8B93]">
              <li className="flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-[#00D4AA]" /> Documented AI governance policies</li>
              <li className="flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-[#00D4AA]" /> Zero data retention on AI processing</li>
              <li className="flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-[#00D4AA]" /> AI transparency disclosures</li>
              <li className="flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-[#00D4AA]" /> ISO 42001-ready framework</li>
            </ul>
          </div>
          <div className="rounded-xl border border-[#1C1C24] bg-[#111116] p-6">
            <h2 className="text-lg font-bold text-[#F1F1F3]">Data Encryption</h2>
            <p className="mt-2 text-sm text-[#8B8B93]">All customer data is encrypted at rest using AES-256 and in transit using TLS 1.3. API keys and secrets are stored using Cloudflare Workers Secrets.</p>
            <ul className="mt-4 space-y-2 text-sm text-[#8B8B93]">
              <li className="flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-[#00D4AA]" /> AES-256 encryption at rest</li>
              <li className="flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-[#00D4AA]" /> TLS 1.3 in transit</li>
              <li className="flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-[#00D4AA]" /> Zero data retention with AI providers</li>
              <li className="flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-[#00D4AA]" /> Secrets encrypted at rest</li>
            </ul>
          </div>
          <div className="rounded-xl border border-[#1C1C24] bg-[#111116] p-6">
            <h2 className="text-lg font-bold text-[#F1F1F3]">Infrastructure Security</h2>
            <p className="mt-2 text-sm text-[#8B8B93]">Spire runs on Cloudflare Workers with data stored in Neon PostgreSQL on AWS. Both Cloudflare and Neon maintain SOC 2 certifications covering their infrastructure.</p>
            <ul className="mt-4 space-y-2 text-sm text-[#8B8B93]">
              <li className="flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-[#00D4AA]" /> Cloudflare Workers edge network</li>
              <li className="flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-[#00D4AA]" /> Neon PostgreSQL (AWS-hosted, SOC 2 certified)</li>
              <li className="flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-[#00D4AA]" /> Uptime monitoring and alerting</li>
              <li className="flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-[#00D4AA]" /> No self-managed servers</li>
            </ul>
          </div>
        </div>

        <div className="mt-14 rounded-xl border border-[#1C1C24] bg-[#111116] p-6">
          <h2 className="text-lg font-bold text-[#F1F1F3]">Compliance documentation</h2>
          <p className="mt-2 text-sm text-[#8B8B93]">We provide the following documentation to customers under NDA during procurement. Contact us to request access.</p>
          <div className="mt-4 grid gap-3 text-sm md:grid-cols-2">
            <div className="rounded-lg bg-[#1C1C24] px-4 py-3"><span className="font-medium text-[#F1F1F3]">Compliance Status Report</span><br /><span className="text-[#5C5C66]">Generated by our platform, on-demand</span></div>
            <div className="rounded-lg bg-[#1C1C24] px-4 py-3"><span className="font-medium text-[#F1F1F3]">Data Processing Agreement</span><br /><span className="text-[#5C5C66]">Standard DPA available on request</span></div>
            <div className="rounded-lg bg-[#1C1C24] px-4 py-3"><span className="font-medium text-[#F1F1F3]">Subprocessor List</span><br /><span className="text-[#5C5C66]">Current subprocessor inventory</span></div>
            <div className="rounded-lg bg-[#1C1C24] px-4 py-3"><span className="font-medium text-[#F1F1F3]">Self-Assessment Questionnaire</span><br /><span className="text-[#5C5C66]">SOC 2 control self-assessment</span></div>
          </div>
        </div>

        <div className="mt-10 text-center">
          <p className="text-sm text-[#5C5C66]">Security questions? Contact us at <span className="text-[#00D4AA]">hello@synov8studio.com</span></p>
        </div>
      </section>

      <footer className="border-t border-[#1C1C24] py-10">
        <div className="mx-auto flex max-w-6xl items-center justify-between px-6">
          <span className="text-sm font-bold tracking-tight text-[#F1F1F3]">Spire</span>
          <div className="flex items-center gap-6 text-sm text-[#5C5C66]">
            <Link to="/blog" className="hover:text-[#8B8B93] transition-colors">Blog</Link>
            <Link to="/privacy" className="hover:text-[#8B8B93] transition-colors">Privacy</Link>
            <Link to="/terms" className="hover:text-[#8B8B93] transition-colors">Terms</Link>
            <span>&copy; {new Date().getFullYear()} Synov8 Ltd.</span>
          </div>
        </div>
      </footer>
    </PublicLayout>
  );
}
